[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
silence = { version = "0.1.3", features = ["client"] }
tokio = { workspace = true }
uuid = { workspace = true }
common = { path = "../common/" }
