[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../common" }
silence = { version = "0.1.3", features = ["server", "video"] }
tokio = { workspace = true }
